/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBConnection;

/**
 *
 * @author vinic
 */
public class MainScreen extends javax.swing.JFrame {

    DBConnection dbc = new DBConnection();
    
    public MainScreen() {
        initComponents();
        dbc.getCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameWelcome = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonRegisterDoctor = new javax.swing.JButton();
        jButtonRegisterNurse = new javax.swing.JButton();
        jButtonRegisterPatient = new javax.swing.JButton();
        jLabelBackgroundPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCloseWelcome = new javax.swing.JButton();
        jLabelMainBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegister = new javax.swing.JMenu();
        jMenuItemDoctors = new javax.swing.JMenuItem();
        jMenuItemPatients = new javax.swing.JMenuItem();
        jMenuItemNurses = new javax.swing.JMenuItem();
        jMenuItemUsers = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemWelcomeScreen = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrameWelcome.setTitle("Welcome");
        jInternalFrameWelcome.setVisible(true);
        jInternalFrameWelcome.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jLabel2.setText("Register");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(20, 10, 100, 14);

        jLabel3.setText("Schedule");
        jPanelInternal.add(jLabel3);
        jLabel3.setBounds(20, 150, 60, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agenda.png"))); // NOI18N
        jButton1.setToolTipText("Scheduling");
        jPanelInternal.add(jButton1);
        jButton1.setBounds(20, 180, 120, 100);

        jButtonRegisterDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CadMedicos.png"))); // NOI18N
        jButtonRegisterDoctor.setToolTipText("Doctor");
        jButtonRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterDoctorActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonRegisterDoctor);
        jButtonRegisterDoctor.setBounds(20, 30, 120, 100);

        jButtonRegisterNurse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-infermeira.png"))); // NOI18N
        jButtonRegisterNurse.setToolTipText("Nurse");
        jPanelInternal.add(jButtonRegisterNurse);
        jButtonRegisterNurse.setBounds(150, 30, 110, 100);

        jButtonRegisterPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadPacientes.png"))); // NOI18N
        jButtonRegisterPatient.setToolTipText("Patient");
        jPanelInternal.add(jButtonRegisterPatient);
        jButtonRegisterPatient.setBounds(263, 30, 110, 100);

        jLabelBackgroundPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internalframe.png"))); // NOI18N
        jPanelInternal.add(jLabelBackgroundPanel);
        jLabelBackgroundPanel.setBounds(4, -6, 960, 370);

        jInternalFrameWelcome.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(-10, 60, 960, 340);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Manager System");
        jInternalFrameWelcome.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 170, 22);

        jButtonCloseWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButtonCloseWelcome.setToolTipText("Close Welcome Screen");
        jButtonCloseWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseWelcomeActionPerformed(evt);
            }
        });
        jInternalFrameWelcome.getContentPane().add(jButtonCloseWelcome);
        jButtonCloseWelcome.setBounds(910, 0, 30, 30);

        getContentPane().add(jInternalFrameWelcome);
        jInternalFrameWelcome.setBounds(0, 20, 970, 450);

        jLabelMainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelMainBackground);
        jLabelMainBackground.setBounds(-6, -6, 980, 480);

        jMenuRegister.setText("Register");

        jMenuItemDoctors.setText("Doctors");
        jMenuItemDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDoctorsActionPerformed(evt);
            }
        });
        jMenuRegister.add(jMenuItemDoctors);

        jMenuItemPatients.setText("Patients");
        jMenuRegister.add(jMenuItemPatients);

        jMenuItemNurses.setText("Nurses");
        jMenuRegister.add(jMenuItemNurses);

        jMenuItemUsers.setText("Users");
        jMenuRegister.add(jMenuItemUsers);

        jMenuBar1.add(jMenuRegister);

        jMenuReport.setText("Report");
        jMenuBar1.add(jMenuReport);

        jMenuTools.setText("Tools");

        jMenuItemWelcomeScreen.setText("Welcome Screen");
        jMenuItemWelcomeScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWelcomeScreenActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuItemWelcomeScreen);

        jMenuBar1.add(jMenuTools);

        jMenuExit.setText("Exit");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuExit.add(jMenuItemExit);

        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(986, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseWelcomeActionPerformed
        jInternalFrameWelcome.dispose();
    }//GEN-LAST:event_jButtonCloseWelcomeActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemWelcomeScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWelcomeScreenActionPerformed
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemWelcomeScreenActionPerformed

    private void jMenuItemDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDoctorsActionPerformed
        DoctorForm df = new DoctorForm();
        df.setVisible(true);
    }//GEN-LAST:event_jMenuItemDoctorsActionPerformed

    private void jButtonRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterDoctorActionPerformed
        DoctorForm df = new DoctorForm();
        df.setVisible(true); 
    }//GEN-LAST:event_jButtonRegisterDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCloseWelcome;
    private javax.swing.JButton jButtonRegisterDoctor;
    private javax.swing.JButton jButtonRegisterNurse;
    private javax.swing.JButton jButtonRegisterPatient;
    private javax.swing.JInternalFrame jInternalFrameWelcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBackgroundPanel;
    private javax.swing.JLabel jLabelMainBackground;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemDoctors;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemNurses;
    private javax.swing.JMenuItem jMenuItemPatients;
    private javax.swing.JMenuItem jMenuItemUsers;
    private javax.swing.JMenuItem jMenuItemWelcomeScreen;
    private javax.swing.JMenu jMenuRegister;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
